name: ib_advanced_regression
channels:
  - conda-forge
dependencies:
  - arviz=0.14.0
  - bambi=0.13.0
  - black-jupyter
  - isort
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_nbextensions_configurator=0.4.1
  - jupyter=1.0.0
  - jupyterlab=3.4.3
  - pip=22.1.2
  - pymc=5.9.1
  - python-graphviz
  - python=3.10
  - matplotlib=3.5.2
  - rise=5.7.1
